# netlify.toml
# Configuration for deploying API Keymaster to Netlify

[build]
  # Directory with the serverless functions
  functions = "netlify/functions"
  # Command to build your site
  command = "npm install"
  # Directory that will be deployed
  publish = "public"

# Redirect all requests to the API endpoint
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Environment variable settings (don't put actual secrets here)
[build.environment]
  NODE_VERSION = "16"
